| Colonne                      | Traduction française                            | Signification métier                      |
| ---------------------------- | ----------------------------------------------- | ----------------------------------------- |
| UniqueID                     | Identifiant unique                              | Identifie chaque client (clé de jointure) |
| next_3m_txn_count            | Nombre de transactions sur les 3 prochains mois | Volume d’activité future du client        |
| BirthDate                    | Date de naissance                               | Permet de calculer l’âge                  |
| Gender                       | Sexe                                            | Homme / Femme / autre                     |
| IncomeCategory               | Catégorie de revenu                             | Classe de revenu (faible, moyen, élevé…)  |
| CustomerStatus               | Statut du client                                | Actif, inactif, suspendu…                 |
| ClientType                   | Type de client                                  | Particulier, entreprise, VIP…             |
| MaritalStatus                | Statut matrimonial                              | Célibataire, marié, divorcé…              |
| OccupationCategory           | Catégorie professionnelle                       | Étudiant, salarié, entrepreneur…          |
| IndustryCategory             | Secteur d’activité                              | Finance, agriculture, commerce…           |
| CustomerBankingType          | Type de relation bancaire                       | Client basique, premium, corporate…       |
| CustomerOnboardingChannel    | Canal d’ouverture de compte                     | Agence, mobile, en ligne…                 |
| ResidentialCityName          | Ville de résidence                              | Localisation du client                    |
| CountryCodeNationality       | Pays de nationalité                             | Code du pays du client                    |
| AnnualGrossIncome            | Revenu annuel brut                              | Revenu total annuel avant impôts          |
| LowIncomeFlag                | Indicateur faible revenu                        | Oui/Non ou 0/1 pour revenu faible         |
| CertificationTypeDescription | Type de certification                           | Diplômes ou certifications du client      |
| ContactPreference            | Préférence de contact                           | Email, téléphone, SMS…                    |

In [17]:
import pandas as pd

In [18]:
df_train = pd.read_csv("../data/raw/Train.csv")
df_demo = pd.read_parquet("../data/raw/demographics_clean.parquet")
df_raw  = df_train.merge(df_demo ,on="UniqueID", how="left")

In [19]:
df_raw.head(10)

,UniqueID,next_3m_txn_count,BirthDate,Gender,IncomeCategory,CustomerStatus,ClientType,MaritalStatus,OccupationCategory,IndustryCategory,CustomerBankingType,CustomerOnboardingChannel,ResidentialCityName,CountryCodeNationality,AnnualGrossIncome,LowIncomeFlag,CertificationTypeDescription,ContactPreference
0,00093e2d-9e1e-4061-ad27-a79b8ff9e165,129,1956-10-26,M,High Income,Active Customer,Individual – Adult,Not Married,Management / Executive,"Finance, Insurance & Real Estate",PRIMARY,FACE-TO-FACE,MILNERTON,ZA,2244579.16,N,Not Disclosed / Unknown,Opted Out
1,0011d60f-a4e2-4333-81fc-2d557a82109b,16,1967-11-11,M,High Income,Active Customer,Individual – Adult,Married,Management / Executive,Households / Individuals,PRIMARY,FACE-TO-FACE,EDENVALE,ZA,1251211.80,N,Not Disclosed / Unknown,Opted Out
2,0016f1e2-64c1-4c65-a668-1dc6bf3b5875,117,1978-04-27,M,Middle Income,Active Customer,Individual – Adult,Not Married,Other / Unclassified,Professional & Business Services,PRIMARY,FACE-TO-FACE,JOHANNESBURG,ZA,344297.42,N,Tertiary Education,No Response
3,001aa3c5-632d-435e-a421-cc3615ccef4d,70,1961-02-19,F,Very High Income,Active Customer,Individual – Adult,Not Married,Management / Executive,Manufacturing,PRIMARY,FACE-TO-FACE,MIDRAND,ZA,1846455.79,N,Not Disclosed / Unknown,Opted In
4,00298c6f-4f9d-4f28-b72c-ad0e56e9eb84,393,1975-08-29,M,Very High Income,Active Customer,Individual – Adult,Not Married,Management / Executive,"Finance, Insurance & Real Estate",PRIMARY,FACE-TO-FACE,ROODEPOORT,ZA,2176785.64,N,Not Disclosed / Unknown,Opted Out
5,00311e57-09d7-4908-8e27-9bb6e4720286,72,1959-05-27,M,High Income,Active Customer,Individual – Adult,Married,Management / Executive,"Finance, Insurance & Real Estate",PRIMARY,FACE-TO-FACE,JOHANNESBURG,ZA,1436566.35,N,Tertiary Education,Opted Out
6,00330c85-a6b6-4089-a64a-7a0a6999d24a,18,2007-10-07,M,Low Income,Active Customer,Individual – Minor,Not Married,Not Economically Active,Households / Individuals,NaN,FACE-TO-FACE,MIDRAND,ZA,6120.16,Y,Not Disclosed / Unknown,Opted Out
7,0035ddb5-1120-4c13-8ad8-be275345fffa,106,1936-09-21,M,High Income,Active Customer,Individual – Adult,Married,Management / Executive,"Finance, Insurance & Real Estate",PRIMARY,FACE-TO-FACE,JOHANNESBURG,ZA,1483121.76,N,Secondary Education,Opted In
8,00394f7b-acad-4cf0-bc8c-32ac3f1733b9,152,1985-08-28,M,Not Disclosed / Unknown,Active Customer,Individual – Adult,Not Disclosed / Unknown,Not Economically Active,Households / Individuals,PRIMARY,FACE-TO-FACE,MILNERTON,ZA,0.00,Y,Not Disclosed / Unknown,Opted Out
9,0044942a-ac2b-414d-b8b2-46b280cf0b97,280,1985-09-29,M,High Income,Active Customer,Individual – Adult,Not Married,Management / Executive,"Finance, Insurance & Real Estate",PRIMARY,FACE-TO-FACE,NOT APPLICABLE,ZA,1493837.37,N,Tertiary Education,Opted Out

In [20]:
df_raw.shape

(8360, 18)

In [21]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 8360 entries, 0 to 8359
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   UniqueID                      8360 non-null   object
 1   next_3m_txn_count             8360 non-null   int64
 2   BirthDate                     8360 non-null   datetime64[ns]
 3   Gender                        8334 non-null   str
 4   IncomeCategory                8360 non-null   str
 5   CustomerStatus                8360 non-null   str
 6   ClientType                    8360 non-null   str
 7   MaritalStatus                 8360 non-null   str
 8   OccupationCategory            8360 non-null   str
 9   IndustryCategory              8360 non-null   str
 10  CustomerBankingType           8081 non-null   str
 11  CustomerOnboardingChannel     8359 non-null   str
 12  ResidentialCityName           8349 non-null   str
 13  CountryCodeNationality        8353 non-null   str
 14  AnnualGrossIncome             7838 non-null   float64
 15  LowIncomeFlag                 8331 non-null   str
 16  CertificationTypeDescription  8360 non-null   str
 17  ContactPreference             8360 non-null   str
dtypes: datetime64[ns](1), float64(1), int64(1), object(1), str(14)
memory usage: 2.5+ MB

In [22]:
df_raw.describe()

       next_3m_txn_count                      BirthDate  AnnualGrossIncome
count        8360.000000                           8360       7.838000e+03
mean          144.969019  1962-04-13 23:22:06.315789472       1.328170e+06
min             1.000000            1890-02-14 00:00:00       0.000000e+00
25%            35.000000            1951-03-05 00:00:00       5.827710e+03
50%           102.000000            1960-05-25 12:00:00       6.327552e+05
75%           201.000000            1970-12-09 00:00:00       1.528389e+06
max          1794.000000            2015-09-29 00:00:00       5.480450e+08
std           152.156725                            NaN       9.431348e+06

In [23]:
df_raw.isna().sum().sort_values(ascending=False)

AnnualGrossIncome               522
CustomerBankingType             279
LowIncomeFlag                    29
Gender                           26
ResidentialCityName              11
CountryCodeNationality            7
CustomerOnboardingChannel         1
UniqueID                          0
next_3m_txn_count                 0
BirthDate                         0
IndustryCategory                  0
OccupationCategory                0
MaritalStatus                     0
ClientType                        0
CustomerStatus                    0
IncomeCategory                    0
CertificationTypeDescription      0
ContactPreference                 0
dtype: int64

In [24]:
df_raw.duplicated().sum()

np.int64(0)